// Removes the build artifacts generated by the per-package bundler runs.
//
// Each `packages/<id>` emits one `<bundler>-dist/` directory per bundler (see
// BUNDLERS in cases.mjs) plus a `.parcel-cache/` from parcel. These are all
// gitignored, but they accumulate across runs and there was previously no way
// to wipe them. This script deletes every `*-dist/` and `.parcel-cache/` under
// `packages/`, leaving sources untouched.
//
// Usage:
//   node scripts/clean.mjs

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PACKAGES = path.join(ROOT, "packages");

/** True for a directory name we treat as a removable build artifact. */
function isArtifactDir(name) {
  return name.endsWith("-dist") || name === ".parcel-cache";
}

function main() {
  if (!fs.existsSync(PACKAGES)) {
    console.error(`No packages directory found at ${PACKAGES}.`);
    process.exit(1);
  }

  const pkgs = fs
    .readdirSync(PACKAGES, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  let removed = 0;
  for (const pkg of pkgs) {
    const pkgDir = path.join(PACKAGES, pkg);
    for (const entry of fs.readdirSync(pkgDir, { withFileTypes: true })) {
      if (!entry.isDirectory() || !isArtifactDir(entry.name)) continue;
      const target = path.join(pkgDir, entry.name);
      fs.rmSync(target, { recursive: true, force: true });
      console.log(`removed ${path.relative(ROOT, target)}`);
      removed += 1;
    }
  }

  console.log(
    removed === 0
      ? "Nothing to clean."
      : `Cleaned ${removed} artifact ${removed === 1 ? "directory" : "directories"}.`,
  );
}

main();
